apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello_world_flask
  labels:
    app: hello_world_flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello_world_flask
  template:
    metadata:
      labels:
        app: hello_world_flask
    spec:
      containers:
      - name: hello_world_flask
        image: marolinejohnson/hello_world_flask:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000