apiVersion: v1
kind: Service
metadata:
  name: hello_world_flask
spec:
  selector:
    app: hello_world_flask
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30443
  type: NodePort